function create_acc_fig(X1, Y1, x_label, y_label)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 20-Jan-2016 14:12:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
%plot(X1,Y1,'MarkerSize',0.01,'Marker','.','LineStyle','none');
plot(X1,Y1,'MarkerSize',0.01,'Marker','.','LineStyle','none');

% Create xlabel
xlabel(x_label);

% Create ylabel
ylabel(y_label);

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.5 0.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-30 40]);
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'XGrid','on','YGrid','on');
