close all;
clear all;
%%
files = importdata('files.txt');
figure, hold on;
ed = [];
ez = [];
for i=1:length(files)
    fprintf('%s\n', char(files(i)));
    [err, ed(i), ez(i)] = depth_err( char(files(i)));
    plot( err(:,1), err(:,2),'.', 'MarkerSize', 24);
    clear err;
%   waitforbuttonpress;
end
grid on;
hXLabel = xlabel('Distamce (m)');
hYLabel = ylabel('Error (m)');
set( gca                       , ...
    'FontName'   , 'Helvetica' );
set([hXLabel, hYLabel], ...
    'FontName'   , 'AvantGarde');
set([ gca]             , ...
    'FontSize'   , 8           );
set([hXLabel, hYLabel]  , ...
    'FontSize'   , 10          );
set(gca, ...
  'Box'         , 'off'     , ...
  'TickDir'     , 'out'     , ...
  'TickLength'  , [.02 .02] , ...
  'XMinorTick'  , 'on'      , ...
  'YMinorTick'  , 'on'      , ...
  'YGrid'       , 'on'      , ...
   'LineWidth'   , 1         );
set(gcf, 'PaperPositionMode', 'auto');
