# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

topics:
-
  name    : vservo
  topic   : velctrl/cmd_vel
  timeout : 0.5
  priority: 10
-
  name    : abs_vel_ctrl
  topic   : abs_vel_ctrl/cmd_vel
  timeout : 0.5
  priority: 50
-
  name    : joystick
  topic   : joy/cmd_vel
  timeout : 0.5
  priority: 100
-
  name    : visual_joy
  topic   : visual_joy/cmd_vel
  timeout : 0.1
  priority: 99
